import {Button} from '@components/Cursor/button'

export default () => (
  <div>
    <h1>Simple Storybook Example</h1>
    <Button />
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae recusandae maxime itaque officiis rem totam alias, non error blanditiis quibusdam laudantium impedit deserunt saepe ut facere beatae dignissimos distinctio nobis.
    Consequuntur amet quisquam impedit laborum blanditiis fugiat magni eius cupiditate ex atque, mollitia tenetur pariatur iste? Est quod delectus illum eius atque, debitis aspernatur ut error neque iure? Facere, dicta.
    Deleniti distinctio provident cumque asperiores hic beatae, at sint alias doloremque aspernatur fuga ex dolorem quas labore nulla voluptatum minima laborum cupiditate quod illo quis assumenda voluptas possimus repellendus? Laborum.
    Totam, recusandae voluptate officiis vel, veniam iste quasi exercitationem animi maiores quos vero est necessitatibus facilis inventore eaque qui. Nemo odit commodi eligendi voluptatem, molestias animi delectus voluptate ratione quaerat.
    Quam tempore velit est veritatis, soluta rem omnis repellendus cupiditate ratione, autem officiis quidem distinctio consequuntur fugit ea rerum, praesentium tempora suscipit. Ullam odio nulla nam dicta, quasi voluptatibus unde.
    Velit eius sunt, placeat perspiciatis fugiat optio, numquam reprehenderit, delectus illo aliquid voluptatum. Aut ipsa mollitia, facilis eveniet assumenda dolorem labore possimus, cupiditate accusantium harum, quas consequatur ab. Exercitationem, quasi!
    Animi, ipsa dicta, iusto eum reprehenderit harum ratione ex totam nesciunt, sapiente eaque neque! Porro aperiam ut nostrum. Illum reiciendis corrupti nobis corporis laudantium tempora nemo excepturi est, fuga quae.
    Obcaecati sequi doloribus dolore quia quod! Fuga odit libero voluptates, accusamus quod esse similique eligendi fugit. Dolorem, laboriosam nemo sint recusandae in provident nisi natus ducimus repellendus laborum magnam quas!
    Veritatis voluptas ut, officiis a reprehenderit saepe excepturi eius repellat possimus quia totam magni iure minima sit. Deserunt possimus adipisci est, cupiditate excepturi facere ea animi, dignissimos, veritatis sed in.
    Quaerat architecto blanditiis dolores, voluptates quidem eius tempora corporis natus nostrum nulla eos cupiditate vel corrupti amet culpa reprehenderit dolore ducimus doloribus, praesentium voluptatibus? Hic quisquam asperiores dolore cumque quaerat!
    Aspernatur numquam impedit, voluptate dolorum odit ullam placeat! Modi quas temporibus aspernatur minima nostrum iure, labore pariatur laborum omnis officia aut quo deserunt blanditiis debitis reiciendis, placeat repudiandae voluptatum soluta.
    Modi in iure amet temporibus! Tempore debitis culpa iure laudantium, magni sequi earum porro! Nulla quibusdam aut esse nihil recusandae sunt exercitationem, aliquam blanditiis, voluptates harum consectetur repudiandae corporis adipisci.
    Facere nobis soluta reprehenderit eos, sapiente modi enim natus voluptatum. Praesentium nesciunt explicabo ratione ab quis laudantium, ut odit animi at, nisi ipsam iure, voluptatem reprehenderit quia sapiente doloribus dignissimos?
    Ratione laudantium ipsum velit alias nemo deserunt ducimus eveniet corrupti eaque necessitatibus voluptatum nihil labore, voluptate fugit, facilis esse voluptas molestiae, doloribus tempore cumque enim temporibus pariatur. Provident, cum perspiciatis.
    Maxime officiis doloremque recusandae commodi beatae alias sunt quidem iste ipsum quae in accusamus eum, expedita harum necessitatibus ullam nam maiores, perspiciatis itaque atque aut numquam repudiandae eveniet autem? Modi.
    Exercitationem repellendus doloremque, incidunt voluptatem delectus illo! Porro minima id ipsam accusamus officiis ipsa? Cumque dolores molestias est ducimus deleniti repudiandae tempora obcaecati, et iure accusamus? Debitis atque repudiandae suscipit.
    Necessitatibus distinctio nulla in asperiores, eum aliquam voluptatem officia alias quasi ut reiciendis aut rem voluptatibus nam atque architecto amet quo provident ipsam excepturi commodi itaque vitae rerum quaerat! Nemo.
    Blanditiis, voluptatem quos! Consectetur, sit officia fugit at doloremque eum mollitia eos dicta ratione. Provident minima earum, hic expedita sint repellendus nam facilis tempora, commodi officia suscipit cumque consectetur nemo!
    Optio quisquam reiciendis sed molestiae libero recusandae fugit, minus vel aliquid doloribus omnis numquam impedit consectetur? Similique earum cumque corporis iusto. Voluptates, dolorem facilis ad non eos neque reprehenderit commodi?
    Nobis suscipit consequatur sed quod optio inventore quis blanditiis voluptates vero fugiat omnis doloremque assumenda animi velit autem tempora accusantium, accusamus consectetur sapiente possimus ipsum reiciendis minus quisquam. Quod, laudantium.
    Non provident nam ipsa est neque officiis, quo recusandae nemo eum molestias repellat commodi, et ad vitae labore facilis quos itaque totam hic quam corporis sequi magni. Doloribus, perferendis cum.
    Et commodi ad modi hic a sequi quod ducimus possimus. Quod doloremque cum at ipsum deserunt temporibus eligendi laboriosam magnam. Nam quas ab saepe consectetur repellat? Qui repellendus illo sequi!
    Neque, aspernatur. Similique sit debitis porro, tempora reiciendis, possimus sapiente id consectetur dolor architecto iure? Modi consequuntur qui magnam ab pariatur obcaecati quia, similique blanditiis praesentium dignissimos fuga minus illo!
    Ea asperiores unde dolore eveniet, nam aspernatur repellat expedita esse eos error libero corporis iusto beatae at, eum laboriosam recusandae enim sed? Maiores eius sunt illo molestiae possimus impedit provident.
    Minima dolorem natus dolor dicta dolorum ipsum vero corrupti officia modi sint a atque quae sapiente quas molestias fugit animi, consequuntur similique. Nulla natus non consectetur, eaque neque saepe tenetur.
    Officiis ducimus, amet perferendis, dicta soluta vel mollitia facere ipsam dolorum quasi minus similique animi, deserunt aliquam voluptas excepturi omnis totam et alias odio maiores dolores aliquid cum incidunt. Perferendis?
    Enim iste impedit voluptatem unde. Fuga ipsa odio magni unde cumque culpa! Ipsum velit culpa placeat perferendis? Sequi cum, debitis possimus quia similique beatae rerum corrupti distinctio, fuga reiciendis itaque.
    Assumenda quo, quod veritatis suscipit nobis atque, aliquid consequuntur voluptates quasi illo minima! Quod rerum tenetur veniam quaerat iusto, dolores, ea fugiat esse, eius porro magni dolorum labore doloremque consequatur?
    Reiciendis praesentium tempora nihil error ipsum in aspernatur repellendus ad porro minima vero, repudiandae quisquam inventore blanditiis molestias veniam labore, id similique voluptatum magnam, expedita quod. Maiores beatae amet qui!
    Pariatur architecto aperiam aspernatur blanditiis error fugiat asperiores nemo iure. Debitis accusamus ipsum id hic porro sint laudantium, laborum distinctio, quae expedita exercitationem accusantium praesentium aspernatur ipsam incidunt, qui fugit.
    Odit debitis amet odio deserunt fugiat labore dicta rerum, porro necessitatibus autem dolore dolorem repellendus provident impedit eligendi voluptatibus illum fuga nesciunt. Debitis fuga perspiciatis error distinctio harum minima sed.
    Odio laborum necessitatibus dolorum ea, saepe, libero quaerat explicabo est voluptas vel laudantium facilis porro blanditiis ratione autem nulla dolorem. Sunt, suscipit? Laboriosam quasi magnam, molestias illo rerum sed harum!
    Veniam facere nobis, nemo dolore repellendus quam harum hic inventore quidem fugiat rem eius rerum illum vero reiciendis impedit quibusdam. Sed laborum neque animi veritatis nihil modi perferendis voluptates tempora?
    Ducimus harum quasi aperiam esse expedita enim officiis quia minima molestias! Quod quo alias voluptate nam corrupti molestiae repellendus quis blanditiis, illo possimus dignissimos minus, earum corporis repellat. Sint, veritatis.
    Nesciunt, suscipit! Rerum, et! Perferendis asperiores eum laboriosam. Repellendus alias reprehenderit ipsa architecto est odit doloribus suscipit amet sapiente! Placeat ea quis quas vel, quasi molestiae repellat dicta ut corrupti.
    Neque voluptates quo sunt reiciendis, autem nostrum quis minima consequuntur modi dolor quisquam voluptate at voluptatibus! Quia enim cupiditate accusamus optio, inventore eaque ducimus possimus praesentium aliquam cum amet delectus!
    Architecto deleniti neque maiores. Dignissimos illo officiis, blanditiis voluptas obcaecati magni doloremque numquam odit id? Id in harum placeat porro eligendi, impedit aut explicabo qui ut alias dolorem, aperiam ratione.
    Dignissimos ipsam officiis et ab. Ad accusamus, deserunt et consequatur error nulla earum? Necessitatibus eos voluptate asperiores. Blanditiis explicabo cupiditate quisquam architecto ea voluptatum a consequatur ex, quae, dolores nulla.
    Commodi tempora animi aspernatur recusandae similique enim amet tempore dolorem vero debitis odit sunt quia, deserunt voluptatum! Rerum dolorem libero eligendi ducimus, earum suscipit delectus doloribus. Ea iste doloribus totam?
    Iure totam voluptas dolores veniam necessitatibus quisquam ab non exercitationem earum illo? Dolorem quas reprehenderit dignissimos placeat ea aspernatur rerum quis! Ducimus possimus iste excepturi nostrum quae ea reprehenderit numquam!
    Laborum doloremque quibusdam nisi facilis ratione perferendis amet voluptates assumenda, in obcaecati? Odio, possimus. Dolore tempora deleniti minima nam optio exercitationem. Omnis explicabo optio sit non sequi hic excepturi deserunt.
    Maiores, minus iste autem impedit quo at repellendus aliquam blanditiis odio eaque corporis consequuntur nemo et soluta ipsam mollitia quisquam culpa a porro tempora provident deleniti sed quis similique. Libero.
    Molestiae pariatur impedit magni beatae sit ad omnis, dolore ratione recusandae. Esse asperiores dolorem dolores omnis debitis magni, minima, minus natus qui odio quaerat enim consequuntur, voluptate reiciendis dignissimos? Quod.
    Nihil quia voluptate architecto sapiente molestias nam, rem doloribus maxime illo ex! Dolor, libero. Id ipsam possimus quia, sint expedita dolorum tempora natus quis blanditiis ratione veritatis neque omnis quo.
    Consequuntur excepturi vitae perspiciatis, nesciunt necessitatibus neque laudantium voluptas voluptatum enim aspernatur, nobis quibusdam quaerat non, obcaecati cum saepe sit minima a. Atque impedit magni illo non porro quo unde.
    Atque dolor maiores molestiae, labore unde esse quis. Reiciendis repudiandae, corporis nesciunt, facere beatae sequi aut necessitatibus fugiat dolores fuga, ex sed hic unde excepturi perferendis explicabo consequuntur vel sint.
    Inventore enim ab doloremque. Vitae, sint delectus. Illo expedita dignissimos, voluptate harum voluptates tenetur voluptatum, qui debitis rerum veniam ut esse! Quod, quibusdam. Ipsum ad molestias molestiae maiores expedita necessitatibus!
    Quasi natus, magni consequatur cumque nihil quae deserunt, dignissimos, laborum ratione cupiditate sequi! Iste minima, dicta voluptas vitae reiciendis, architecto eos laborum sed tenetur ab rem corrupti repellendus inventore adipisci?
    Nobis consectetur ipsam natus saepe consequatur doloremque eligendi porro placeat exercitationem qui assumenda illum earum, explicabo laudantium impedit suscipit cum a quas odio excepturi! Doloremque dolor quisquam animi vero incidunt.
    Quae nam sit minima voluptates vero tenetur laboriosam, cum quibusdam quidem doloremque sed odio reiciendis! Odit recusandae tenetur molestias nulla, fugit obcaecati praesentium perspiciatis, perferendis sunt corporis reprehenderit beatae nihil?
    Veniam quae ipsam blanditiis labore tempore doloremque fuga consequatur repellendus saepe sunt deserunt ab quasi alias recusandae dicta, rerum maiores ullam possimus. Error veritatis sed velit nisi nihil, distinctio quasi.
    Officiis, numquam eum neque reiciendis corporis nostrum recusandae veniam, quia doloribus ab eius autem deleniti assumenda veritatis cupiditate quos, rem consequatur error repudiandae nobis ipsam beatae hic. Nam, pariatur eos?
    Laudantium iure dignissimos dolores cupiditate amet atque magni veritatis similique soluta dicta, neque reprehenderit iusto aperiam ea earum ipsa ad accusantium suscipit repellat deserunt, esse eum accusamus minima voluptas! Odio!
    Doloribus, id qui explicabo numquam impedit ipsam dolor quasi consequatur nam libero deleniti optio quia error aspernatur nihil vitae iusto commodi consequuntur dolorum cum soluta magnam dolorem. Quis, ad iste?
    Modi a odio expedita. Sed, incidunt itaque sint, numquam provident dolorem reprehenderit quas voluptas assumenda illo voluptatibus temporibus, a ea harum perferendis. Eius quidem ratione deserunt, accusamus veritatis sit necessitatibus.
    Magni libero ex quas eveniet impedit omnis vel! Quam fuga sequi deleniti consequuntur? Neque aliquam natus hic ab illum inventore blanditiis, debitis nostrum esse enim vero. Enim eius incidunt provident.
    Optio magni animi corrupti aliquam reiciendis itaque eius, dignissimos quis. Esse, iusto. Cupiditate cum ea, dicta laborum eveniet praesentium modi sunt fugit quasi explicabo in illo assumenda inventore. Distinctio, quae!
    Accusantium sint, iure earum temporibus dolorem a voluptatum. Vitae aliquam non, doloremque quis natus accusamus magnam dolorem libero cupiditate inventore explicabo! Voluptatem non, dolor nam aperiam iusto nisi aliquam earum!
    Molestias voluptates aperiam perferendis aliquid ut facilis cumque laudantium quis dolorum excepturi magnam sapiente alias sequi consectetur temporibus libero, possimus non ipsa! Enim exercitationem qui veritatis placeat facere quaerat ullam.
    Magni eligendi dolores qui, recusandae cum et architecto sed consequuntur laudantium ratione unde quisquam, magnam ad at obcaecati, veniam natus aliquid eius. Similique accusantium officia minus deserunt consectetur vel sequi!
  </div>
)
